### ISSUE TITLE
Acs not working

### ISSUE THREAD

**Issue by 0raid** [gntouts/eltrak#8]
First , congratulations for your work!!

the acs is not working..can you check it out?

**Comment by gntouts** [comment]
Hello, I am glad you like it. I can look into it, but I need some valid tracking numbers for testing.

**Comment by 0raid** [comment]
Thanks 4 your reply! , sure just give me your email to send you a valid tracking number.

**Comment by gntouts** [comment]
You can send it to g.ntouts@outlook.com

**Comment by 0raid** [comment]
Thanks , i have just send you a valid tracking number

**Comment by gntouts** [comment]
They have purposefully blocked the access to their API to non-browser requests:

```bash
$ curl -I https://api.acscourier.net/api/parcels/search/31******85
HTTP/2 404 
request-context: appId=cid-v1:15f2a1b9-f54b-4ec5-8d52-957088116faa
strict-transport-security: max-age=2592000
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
x-rate-limit-limit: 1s
x-rate-limit-remaining: 1
x-rate-limit-reset: 2022-04-16T16:46:02.9034581Z
content-length: 0
cache-control: max-age=0
expires: Sat, 16 Apr 2022 16:46:01 GMT
date: Sat, 16 Apr 2022 16:46:01 GMT
set-cookie: ARRAffinity=f5fcf88be886a23adc2ac57d3d80e73f2d267771ade0e871d857d025595def9c;Path=/;HttpOnly;Secure;Domain=api.acscourier.net
set-cookie: ARRAffinitySameSite=f5fcf88be886a23adc2ac57d3d80e73f2d267771ade0e871d857d025595def9c;Path=/;HttpOnly;SameSite=None;Secure;Domain=api.acscourier.net
```

This is the same API they use for their webpage, but the server only responds if your request headers include a secret key that is saved in the browser's LocalStorage when you visit their website. This cannot be retrieved using Python's `requests` package.

The only workaround is to use Selenium to simulate a headless browser, though this will lead to significantly slower response times. Also, it is very likely that they have implemented some sort of rate-limiting, so header and IP rotation is also required for any production-ready deployment.

I will try to add support for the Selenium workaround, but I am not very optimistic.

**Comment by 0raid** [comment]
ohh i see , thanks anyway , keep up the good job! and let us know if you have any news about this.

**Comment by DanielPikilidis** [comment]
@gntouts Is the fix not working?

**Comment by gntouts** [comment]
> @gntouts Is the fix not working?

I think it is working properly.

**Comment by DanielPikilidis** [comment]
I tried a few different ACS ids and I'm getting this error:

`{
  "detail": "Unknow error: 'items'. Please provide more details for debugging."
}
`

If I clone the repo and run it locally then it's working fine, but for some reason it refuses to work with heroku.

**Comment by gntouts** [comment]
Something went wrong and Heroku was using the previous Docker image. I redeployed the correct image.
